default: &default
  adapter: postgresql
  host: postgres
  port: 5432
  pool: 5
  timeout: 5000
  encoding: unicode
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
development:
  <<: *default
  database: a4ef8q_development
test:
  <<: *default
  database: a4ef8q_test
