default: &default
  adapter: postgresql
  host: db
  port: 5432
  pool: 5
  timeout: 5000
  encoding: unicode
  username: nameless
  password: ZqJOXFWUuG7dSzR92C
development:
  <<: *default
  database: a4ef8q_development
test:
  <<: *default
  database: a4ef8q_test
